import Link from "next/link";
import { ArrowRight, Bike, CircleAlert, CircleCheck, Clock3 } from "lucide-react";
import { PageHeader, Button } from "@/components/page-header";
import { RevenueChart } from "@/components/revenue-chart";
import { StatusPill } from "@/components/status-pill";
import { attention, kpis, partners } from "@/lib/demo-data";
import { compactNumber } from "@/lib/utils";

export default function Dashboard(){return <div><PageHeader eyebrow="OPERATIONS / 2026.08.11" title="今天，把合作往前推一程。" description="签约、车辆、内容与销售归因都汇集在同一条里程线上。先处理 7 个阻塞项，再查看四站表现。" action={<Button>新建合作</Button>}/><div className="space-y-5 p-5 md:p-8">
  <section className="grid gap-px overflow-hidden rounded-[16px] border border-[#e1e5e8] bg-[#e1e5e8] sm:grid-cols-2 xl:grid-cols-4">{kpis.map((k,i)=><Link href={k.href} key={k.label} className="group bg-white p-5 transition-colors hover:bg-[#f4f7f9]"><div className="mb-7 flex items-center justify-between text-[11px] font-semibold text-[#68717a]"><span>{k.label}</span><span className="font-mono text-[#a1a7ad]">0{i+1}</span></div><div className="flex items-end justify-between"><div><div className="font-display text-[32px] font-semibold">{k.value}</div><div className="mt-2 text-[11px] text-[#6f7780]">{k.delta}</div></div><ArrowRight size={15} className="mb-1 text-[#a2a9b0] transition-transform group-hover:translate-x-1"/></div></Link>)}</section>
  <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-[16px] border border-[#e1e5e8] bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-bold">月度 KOL 收入</h2><p className="mt-1 text-[11px] text-[#7b838b]">四站原币种指数趋势</p></div><StatusPill tone="blue">EU · US · CA · BR</StatusPill></div><RevenueChart/></div><div className="rounded-[16px] border border-[#e1e5e8] bg-[#111418] p-5 text-white"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-sm font-bold">待推进</h2><p className="mt-1 text-[11px] text-white/50">按业务风险排序</p></div><CircleAlert size={18} className="text-[#a9bdd2]"/></div><div className="space-y-1">{attention.map((x,i)=><Link href={x.href} key={x.title} className="group block rounded-[11px] border border-white/10 p-3 hover:bg-white/[.05]"><div className="flex items-start gap-3"><span className="font-mono text-[10px] text-white/35">0{i+1}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{x.title}</div><div className="mt-1 text-[10px] leading-4 text-white/50">{x.detail}</div></div><ArrowRight size={13} className="text-white/30 transition-transform group-hover:translate-x-1"/></div></Link>)}</div></div></section>
  <section className="rounded-[16px] border border-[#e1e5e8] bg-white"><div className="flex items-center justify-between border-b border-[#e8ebed] p-5"><div><h2 className="text-sm font-bold">高价值 Partner</h2><p className="mt-1 text-[11px] text-[#7b838b]">销售、内容与可靠性综合评估</p></div><Link href="/partners" className="text-xs font-semibold text-[#4e6b88]">查看全部 →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left"><thead className="text-[10px] uppercase tracking-wider text-[#8a9198]"><tr>{["Partner","市场","内容潜力","订单","归因收入","评分","状态"].map(x=><th className="px-5 py-3 font-semibold" key={x}>{x}</th>)}</tr></thead><tbody>{partners.slice(0,4).map(p=><tr key={p.id} className="border-t border-[#edf0f2] text-xs hover:bg-[#fafbfc]"><td className="px-5 py-3.5"><Link href={`/partners/${p.id}`} className="font-semibold">{p.name}</Link><span className="ml-2 font-mono text-[9px] text-[#9aa0a6]">{p.code}</span></td><td className="px-5 py-3.5">{p.market}</td><td className="px-5 py-3.5 text-[#66707a]">{compactNumber(p.avgViews)} 均播放</td><td className="px-5 py-3.5 font-mono">{p.orders}</td><td className="px-5 py-3.5 font-semibold">{p.revenue.toLocaleString()} {p.currency}</td><td className="px-5 py-3.5"><span className="grid size-7 place-items-center rounded-full border border-[#cdd6df] font-mono text-[10px] font-bold">{p.score}</span></td><td className="px-5 py-3.5"><StatusPill tone={p.status==="活跃"?"good":"blue"}>{p.status}</StatusPill></td></tr>)}</tbody></table></div></section>
  <section className="grid gap-4 md:grid-cols-3"><Link href="/pipeline" className="rounded-[14px] border border-[#e1e5e8] bg-white p-4 hover:bg-[#f4f7f9]"><Bike size={18}/><b className="mt-5 block text-sm">42 段进行中里程</b><p className="mt-1 text-[11px] text-[#747d86]">17 辆车在运输或等待签收</p></Link><Link href="/tasks" className="rounded-[14px] border border-[#e1e5e8] bg-white p-4 hover:bg-[#f4f7f9]"><Clock3 size={18}/><b className="mt-5 block text-sm">12 条内容已逾期</b><p className="mt-1 text-[11px] text-[#747d86]">已自动创建负责人任务</p></Link><Link href="/sales" className="rounded-[14px] border border-[#e1e5e8] bg-white p-4 hover:bg-[#f4f7f9]"><CircleCheck size={18}/><b className="mt-5 block text-sm">87.4% 订单已归因</b><p className="mt-1 text-[11px] text-[#747d86]">18 单等待人工判定</p></Link></section>
</div></div>}
