import Link from "next/link";
import { Filter, Search } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { PartnerForm } from "@/components/crm-actions";
import { prisma } from "@/lib/db";
import { compactNumber } from "@/lib/utils";

export const dynamic = "force-dynamic";
const statusLabel:Record<string,string>={potential:"潜在",contacted:"已联系",replied:"已回复",negotiating:"洽谈中",contracting:"签约中",active:"活跃",paused:"暂停",completed:"已完成",blacklisted:"黑名单"};

export default async function Partners(){
  const [partners,users]=await Promise.all([
    prisma.partner.findMany({where:{archivedAt:null},include:{owner:true,socialAccounts:{orderBy:{isPrimary:"desc"},take:1},collaborations:{where:{archivedAt:null},orderBy:{updatedAt:"desc"},take:1},attributions:{where:{isPrimary:true},select:{attributedRevenue:true,order:{select:{currency:true}}}},scores:{orderBy:{calculatedAt:"desc"},take:1}},orderBy:{updatedAt:"desc"},take:100}),
    prisma.user.findMany({select:{id:true,name:true},orderBy:{name:"asc"}}),
  ]);
  return <div><PageHeader eyebrow="PARTNER DATABASE" title="Partner 主档" description="一个 Partner 只有一份主档，跨平台账号、多轮合作和四站销售都从这里汇总。" action={<PartnerForm users={users}/>}/><div className="p-5 md:p-8"><div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-[240px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8b9299]"/><input className="w-full rounded-[10px] border border-[#dfe3e7] bg-white py-2.5 pl-9 pr-3 text-xs" placeholder="搜索名称、邮箱、handle…"/></div>{["类型","市场","平台","产品","状态","负责人"].map(x=><button key={x} className="rounded-[10px] border border-[#dfe3e7] bg-white px-3 text-[11px] font-semibold">{x} ⌄</button>)}<button className="grid size-9 place-items-center rounded-[10px] border border-[#dfe3e7] bg-white"><Filter size={14}/></button></div><div className="overflow-hidden rounded-[16px] border border-[#e1e5e8] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="bg-[#fafbfc] text-[10px] uppercase tracking-wider text-[#858d95]"><tr>{["Partner","国家 / 市场","平台","粉丝","均播放","活跃产品","订单","收入","分数","负责人","状态"].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{partners.map(p=>{const social=p.socialAccounts[0];const revenue=p.attributions.reduce((sum,x)=>sum+Number(x.attributedRevenue),0);const currency=p.attributions[0]?.order.currency??"—";return <tr className="border-t border-[#ebedef] text-xs hover:bg-[#fafbfc]" key={p.id}><td className="px-4 py-4"><Link href={`/partners/${p.id}`} className="font-semibold hover:text-[#486783]">{p.name}</Link><div className="mt-1 font-mono text-[9px] text-[#a0a6ac]">{p.partnerCode}</div></td><td className="px-4 py-4">{p.creatorCountry||"—"}<div className="mt-1 text-[10px] text-[#8b9299]">{p.targetMarket||"—"}</div></td><td className="px-4 py-4"><b>{social?.platform||"—"}</b><div className="mt-1 text-[10px] text-[#8b9299]">{social?.handle||"—"}</div></td><td className="px-4 py-4 font-mono">{compactNumber(social?.followers??0)}</td><td className="px-4 py-4 font-mono">{compactNumber(social?.avgViews??0)}</td><td className="px-4 py-4">{p.collaborations[0]?.product||"—"}</td><td className="px-4 py-4 font-mono">{p.attributions.length}</td><td className="px-4 py-4 font-semibold">{revenue.toLocaleString()}<div className="text-[9px] text-[#8b9299]">{currency}</div></td><td className="px-4 py-4"><span className="font-mono font-bold">{p.scores[0]?.totalScore?Math.round(Number(p.scores[0].totalScore)):"—"}</span></td><td className="px-4 py-4">{p.owner?.name||"未分配"}</td><td className="px-4 py-4"><StatusPill tone={p.status==="active"?"good":p.status==="blacklisted"?"danger":"blue"}>{statusLabel[p.status]}</StatusPill></td></tr>})}</tbody></table></div><div className="flex items-center justify-between border-t border-[#e7eaed] px-4 py-3 text-[10px] text-[#7d858d]"><span>共 {partners.length} 个 Partner</span><span>显示最近 100 条</span></div></div></div></div>;
}
