import { notFound } from "next/navigation";
import { ArrowUpRight, CalendarClock, CheckCircle2, Circle, Mail, MapPin, MessageSquareText } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { CollaborationForm, DeleteNoteButton, NoteData, NoteForm, PartnerForm, TaskForm, TaskStatusSelect } from "@/components/crm-actions";
import { prisma } from "@/lib/db";
import { compactNumber } from "@/lib/utils";

export const dynamic="force-dynamic";
const noteLabels:Record<string,string>={partner_profile:"长期备注",email:"邮件沟通",proposal:"合作报价",shipment:"样车/物流",content_review:"内容审核",publication:"内容发布",commission:"佣金结算",after_sales:"售后问题",internal:"内部备注",other:"其他"};
const statusLabels:Record<string,string>={todo:"待处理",in_progress:"进行中",waiting_external:"等待对方",done:"已完成",cancelled:"已取消",completed:"已完成",content_production:"内容制作",partially_published:"部分发布",negotiating:"洽谈中",signed:"已签约",shipped:"已发货",delivered:"已签收",paused:"暂停"};
const fmt=(date:Date)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(date);

export default async function PartnerDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  const [p,users]=await Promise.all([
    prisma.partner.findUnique({
      where:{id},
      include:{
        owner:true,
        socialAccounts:{orderBy:{isPrimary:"desc"}},
        collaborations:{
          where:{archivedAt:null},
          include:{owner:true,deliverables:true,workflowSteps:{orderBy:{sequence:"asc"}}},
          orderBy:{updatedAt:"desc"},
        },
        notes:{include:{author:true,collaboration:true},orderBy:{createdAt:"desc"}},
        tasks:{include:{owner:true,collaboration:true},orderBy:{dueDate:"asc"}},
        attributions:{where:{isPrimary:true},select:{attributedRevenue:true}},
        scores:{orderBy:{calculatedAt:"desc"},take:1},
      },
    }),
    prisma.user.findMany({select:{id:true,name:true},orderBy:{name:"asc"}}),
  ]);
  if(!p)notFound();
  const social=p.socialAccounts[0];const score=p.scores[0]?.totalScore?Math.round(Number(p.scores[0].totalScore)):null;const revenue=p.attributions.reduce((s,x)=>s+Number(x.attributedRevenue),0);const current=p.collaborations.find(x=>x.status!=="completed")??p.collaborations[0];
  const collaborationOptions=p.collaborations.map(x=>({id:x.id,name:`${x.product} · ${x.collaborationCode}`,partnerId:p.id,product:x.product}));
  const allPartnerOption=[{id:p.id,name:p.name}];
  return <div><PageHeader eyebrow={`${p.partnerCode} / PARTNER`} title={p.name} description={`${p.creatorCountry||"未填写地区"} · ${social?.platform||"未填写平台"} · ${social?.handle||"未填写账号"}`} action={<div className="flex flex-wrap gap-2"><PartnerForm users={users} partnerId={p.id} initial={{name:p.name,partnerType:p.partnerType,creatorCountry:p.creatorCountry,targetMarket:p.targetMarket,email:p.email,phone:p.phone,status:p.status,ownerUserId:p.ownerUserId,notesText:p.notesText}}/><CollaborationForm partners={allPartnerOption} users={users} fixedPartnerId={p.id}/></div>}/><div className="p-5 md:p-8"><div className="mb-5 flex gap-1 overflow-x-auto border-b border-[#e1e5e8]">{["概览","合作","跟进备注","任务","销售"].map((x,i)=><a href={`#${["overview","collaborations","notes","tasks","sales"][i]}`} className="whitespace-nowrap border-b-2 border-transparent px-4 py-3 text-xs font-semibold text-[#78818a] hover:border-[#111418] hover:text-[#111418]" key={x}>{x}</a>)}</div>
    <section id="overview" className="mb-5 grid gap-px overflow-hidden rounded-[15px] border border-[#e1e5e8] bg-[#e1e5e8] sm:grid-cols-3 lg:grid-cols-6">{[["粉丝",compactNumber(social?.followers??0)],["均播放",compactNumber(social?.avgViews??0)],["合作",String(p.collaborations.length)],["归因订单",String(p.attributions.length)],["归因收入",revenue.toLocaleString()],["KOL Score",score?String(score):"—"]].map(([a,b])=><div className="bg-white p-4" key={a}><span className="text-[10px] text-[#78818a]">{a}</span><b className="mt-4 block font-display text-2xl">{b}</b></div>)}</section>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-5">
      {current&&<section className="rounded-[16px] border border-[#e1e5e8] bg-white p-5"><div className="mb-5 flex justify-between"><div><h2 className="text-sm font-bold">当前合作里程</h2><p className="mt-1 text-[11px] text-[#7a828b]">{current.product} · {current.targetMarket}</p></div><StatusPill tone="blue">{statusLabels[current.status]??current.status}</StatusPill></div><div className="overflow-x-auto pb-2"><div className="flex min-w-[850px] items-start">{current.workflowSteps.map((s,i)=><div className="relative flex flex-1 flex-col items-center" key={s.id}>{i<current.workflowSteps.length-1&&<span className={`absolute left-1/2 top-3 h-px w-full ${s.status==="completed"?"bg-[#5b7695]":"bg-[#dce1e5]"}`}/>}<span className={`relative z-10 grid size-6 place-items-center rounded-full border ${s.status==="completed"?"border-[#5b7695] bg-[#5b7695] text-white":"border-[#cfd5da] bg-white text-[#a0a7ae]"}`}>{s.status==="completed"?<CheckCircle2 size={12}/>:<Circle size={9}/>}</span><span className="mt-2 text-center text-[9px] text-[#646d76]">{s.label}</span></div>)}</div></div>{current.nextAction&&<div className="mt-4 rounded-xl bg-[#f4f7fa] p-3 text-xs"><b>下一步：</b>{current.nextAction}{current.nextActionDate&&<span className="ml-2 text-[#6b7680]">{fmt(current.nextActionDate)}</span>}</div>}</section>}
      <section id="collaborations" className="rounded-[16px] border border-[#e1e5e8] bg-white"><div className="flex items-center justify-between border-b border-[#e8ebed] p-5"><div><h2 className="text-sm font-bold">合作历史</h2><p className="mt-1 text-[10px] text-[#7c858e]">每轮合作独立记录成本、状态和下一行动</p></div><CollaborationForm partners={allPartnerOption} users={users} fixedPartnerId={p.id}/></div>{p.collaborations.length?p.collaborations.map(x=>{const required=x.deliverables.reduce((s,d)=>s+d.requiredQuantity,0);const published=x.deliverables.reduce((s,d)=>s+d.publishedQuantity,0);const progress=required?Math.round(published/required*100):0;return <div key={x.id} className="grid grid-cols-[1fr_auto] items-center gap-5 border-b border-[#edf0f2] p-5 last:border-0"><div><b className="text-sm">{x.product}</b><p className="mt-1 text-[11px] text-[#77808a]">{x.collaborationCode} · {published}/{required||0} 项交付 · {x.owner?.name||"未分配"}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#edf0f2]"><div className="h-full bg-[#5b7695]" style={{width:`${progress}%`}}/></div>{x.nextAction&&<p className="mt-2 text-[10px] text-[#68727b]">下一步：{x.nextAction}</p>}</div><StatusPill tone={x.status==="completed"?"good":"blue"}>{statusLabels[x.status]??x.status}</StatusPill></div>}):<p className="p-8 text-center text-xs text-[#7c858e]">还没有合作记录</p>}</section>
      <section id="notes" className="rounded-[16px] border border-[#e1e5e8] bg-white"><div className="flex items-center justify-between border-b border-[#e8ebed] p-5"><div><h2 className="text-sm font-bold">跟进备注</h2><p className="mt-1 text-[10px] text-[#7c858e]">长期特点与每次合作沟通按时间倒序保留</p></div><NoteForm partnerId={p.id} collaborations={collaborationOptions}/></div>{p.notes.length?<div className="divide-y divide-[#edf0f2]">{p.notes.map(n=>{const note:NoteData={id:n.id,noteType:n.noteType,body:n.body,nextAction:n.nextAction,followUpAt:n.followUpAt?.toISOString()??null,collaborationId:n.collaborationId};return <article key={n.id} className="p-5"><div className="flex items-start gap-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-full bg-[#e8edf3] text-[#5b7695]"><MessageSquareText size={14}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-xs">{noteLabels[n.noteType]}</b>{n.collaboration&&<span className="rounded-full bg-[#f0f2f4] px-2 py-1 text-[9px]">{n.collaboration.product}</span>}<span className="text-[9px] text-[#8a929a]">{n.author?.name||"系统"} · {fmt(n.createdAt)}</span></div><p className="mt-3 whitespace-pre-wrap text-xs leading-6 text-[#343a40]">{n.body}</p>{n.nextAction&&<div className="mt-3 rounded-xl border border-[#dfe7ee] bg-[#f7f9fb] p-3 text-[11px]"><b>下一步：</b>{n.nextAction}{n.followUpAt&&<span className="ml-2 text-[#6b7680]">跟进：{fmt(n.followUpAt)}</span>}</div>}</div><div className="flex gap-1"><NoteForm partnerId={p.id} collaborations={collaborationOptions} initial={note}/><DeleteNoteButton partnerId={p.id} noteId={n.id}/></div></div></article>})}</div>:<p className="p-8 text-center text-xs text-[#7c858e]">还没有备注，点击“新增记录”开始记录第一次沟通。</p>}</section>
      <section id="tasks" className="rounded-[16px] border border-[#e1e5e8] bg-white"><div className="flex items-center justify-between border-b border-[#e8ebed] p-5"><div><h2 className="text-sm font-bold">任务</h2><p className="mt-1 text-[10px] text-[#7c858e]">负责人可直接更新任务状态</p></div><TaskForm partners={allPartnerOption} collaborations={collaborationOptions} users={users} fixedPartnerId={p.id}/></div>{p.tasks.length?p.tasks.map(t=><div key={t.id} className="grid gap-3 border-b border-[#edf0f2] p-4 last:border-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><b className={`text-xs ${t.status==="done"?"text-[#8a929a] line-through":""}`}>{t.title}</b><p className="mt-1 text-[10px] text-[#7c858e]">{t.collaboration?.product||"Partner 通用任务"} · {t.owner?.name||"未分配"} · 截止 {fmt(t.dueDate)}</p></div><TaskStatusSelect taskId={t.id} status={t.status}/></div>):<p className="p-8 text-center text-xs text-[#7c858e]">暂无任务</p>}</section>
    </div><aside className="space-y-5"><section className="rounded-[16px] border border-[#e1e5e8] bg-white p-5"><h2 className="mb-4 text-sm font-bold">主档信息</h2><div className="space-y-4 text-xs"><p className="flex items-center gap-3"><MapPin size={14} className="text-[#82909d]"/>{p.creatorCountry||"未填写"} · 目标 {p.targetMarket||"未填写"}</p><p className="flex items-center gap-3"><Mail size={14} className="text-[#82909d]"/>{p.email||"未填写邮箱"}</p>{social&&<a href={social.profileUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-[#5b7695]"><ArrowUpRight size={14} className="text-[#82909d]"/>{social.handle||social.profileUrl}</a>}<p>负责人：{p.owner?.name||"未分配"}</p></div>{p.notesText&&<div className="mt-4 border-t border-[#edf0f2] pt-4 text-[11px] leading-5 text-[#646d76]">{p.notesText}</div>}</section><section className="rounded-[16px] border border-[#e1e5e8] bg-white p-5"><div className="flex items-center gap-2"><CalendarClock size={15} className="text-[#5b7695]"/><h2 className="text-sm font-bold">近期待办</h2></div><div className="mt-4 space-y-3">{p.tasks.filter(t=>!["done","cancelled"].includes(t.status)).slice(0,5).map(t=><div key={t.id} className="rounded-xl bg-[#f7f8fa] p-3"><b className="text-[11px]">{t.title}</b><p className="mt-1 text-[9px] text-[#7c858e]">{fmt(t.dueDate)} · {statusLabels[t.status]}</p></div>)}{!p.tasks.some(t=>!["done","cancelled"].includes(t.status))&&<p className="text-[11px] text-[#7c858e]">暂无未完成任务</p>}</div></section></aside></div></div></div>;
}
